language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      name: Xenial, Python 3 build
      addons:
        apt:
          packages:
            - cmake
            - libboost-all-dev
            - libsdl2-dev
            - libfreetype6-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libpng-dev
            - libjpeg-dev
            - libbz2-dev
            - libfluidsynth-dev
            - libgme-dev
            - libopenal-dev
            - zlib1g-dev
            - timidity
            - tar
            - nasm
            - wget
            - python3-dev
            - python3-numpy
            - python3-pip
      script:
        - |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON3=ON
          make
    - os: linux
      dist: bionic
      name: Bionic, Python 3 build
      addons:
        apt:
          packages:
            - cmake
            - libboost-all-dev
            - libsdl2-dev
            - libfreetype6-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libpng-dev
            - libjpeg-dev
            - libbz2-dev
            - libfluidsynth-dev
            - libgme-dev
            - libopenal-dev
            - zlib1g-dev
            - timidity
            - tar
            - nasm
            - wget
            - python3-dev
            - python3-numpy
            - python3-pip
      script:
        - |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON3=ON
          make
    - os: osx
      name: MacOS, Python 3 build
      addons:
        homebrew:
          packages:
            - cmake
            - boost
            - sdl2
            - wget
      script:
        - |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON3=ON
          make